package com.taxhouse;

import java.util.Calendar;
import java.util.Date;
import java.util.Map;
import java.util.Set;
import java.util.Iterator;

import com.taxhouse.app.*;
import com.taxhouse.db.*;
import com.taxhouse.model.*;
import com.taxhouse.model.TaxRecord.Entry;

rule "Small Scale Profit Private Class A Federal base rule" #Base Tax
salience 50
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.SMALL) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 && ((categoryId == Organization.Category.getId(Organization.Category.AGRICULTURE) ) || (categoryId==Organization.Category.getId(Organization.Category.EDUCATIONAL)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ARMY) ) || (categoryId == Organization.Category.getId(Organization.Category.HEALTH) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 20;

	int slabId = item.getSlabId();

	if (slabId == 2) {
		percent = percent * 0.5;
	} else if (slabId == 3) {
		percent = percent * 0.7;
	} else {
		percent = percent * 1.1;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Small scale Profit Private Class A organization)", percent, fraction));
 end
 
 rule "Small Scale Profit Private Class A State tax rule" #Base Tax
 salience 48
 when
	  item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.SMALL) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 && ((categoryId == Organization.Category.getId(Organization.Category.AGRICULTURE) ) || (categoryId==Organization.Category.getId(Organization.Category.EDUCATIONAL)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ARMY) ) || (categoryId == Organization.Category.getId(Organization.Category.HEALTH) )
	 ))
	 taxRecord:TaxRecord()
then 
 	double amount = item.getTaxableIncome();
	double percent = 15;

	int slab = item.getSlabId();

	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 13.9;
		} else {
			percent = 15.9;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 1) {
			percent = 14.5;
		} else {
			percent = 16.5;
		}
	}

	else {
		if (slab == 1) {
			percent = 15.0;
		} else {
			percent = 16;
		}
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Small scale Profit Private Class A organization)", percent,
			fraction));
 end   

 rule "Medium Scale Profit Private Class A Federal base rule"  #Base Tax
salience 50
when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.MEDIUM) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 && ((categoryId == Organization.Category.getId(Organization.Category.AGRICULTURE) ) || (categoryId==Organization.Category.getId(Organization.Category.EDUCATIONAL)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ARMY) ) || (categoryId == Organization.Category.getId(Organization.Category.HEALTH) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 25;

	int slabId = item.getSlabId();

	if (slabId == 2) {
		percent = percent * 0.8;
	} else if (slabId == 3) {
		percent = percent * 0.9;
	} else {
		percent = percent * 1.2;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Medium scale Profit Private Class A organization)", percent,
				fraction));   
end
 
 rule "Medium Scale Profit Private Class A State tax rule" #Base Tax
 salience 48
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.MEDIUM) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 && ((categoryId == Organization.Category.getId(Organization.Category.AGRICULTURE) ) || (categoryId==Organization.Category.getId(Organization.Category.EDUCATIONAL)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ARMY) ) || (categoryId == Organization.Category.getId(Organization.Category.HEALTH) )
	 ))
	 taxRecord:TaxRecord()
then
	double amount = item.getTaxableIncome();
	double percent = 0;

	int slab = item.getSlabId();
	
	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 13.9;
		} else {
			percent = 15.9;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 2) {
			percent = 14.5;
		} else {
			percent = 16.5;
		}
	}
	else {
		if (slab == 3) {
			percent = 15.0;
		} else {
			percent = 16;
		}
	}
	
	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Medium scale Profit Private Class A organization)", percent,
			fraction)); 
end  
 
 
 
 rule "Large Scale Profit Private Class A Federal base rule" #Base Tax
salience 50
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.LARGE) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 && ((categoryId == Organization.Category.getId(Organization.Category.AGRICULTURE) ) || (categoryId==Organization.Category.getId(Organization.Category.EDUCATIONAL)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ARMY) ) || (categoryId == Organization.Category.getId(Organization.Category.HEALTH) )
	 ))
	 taxRecord:TaxRecord()
then
	double amount = item.getTaxableIncome();
	double percent = 25;

	int slabId = item.getSlabId();
	if (slabId == 2) {
		percent = percent * 1.2;
	} else if (slabId == 3) {
		percent = percent * 1.4;
	} else {
		percent = percent * 1.6;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Large scale Profit Private Class A organization)", percent,
			fraction));
end
 
 rule "Large Scale Profit Private Class A State tax rule" #Base Tax
 salience 48
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.LARGE) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 && ((categoryId == Organization.Category.getId(Organization.Category.AGRICULTURE) ) || (categoryId==Organization.Category.getId(Organization.Category.EDUCATIONAL)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ARMY) ) || (categoryId == Organization.Category.getId(Organization.Category.HEALTH) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 0;

	int slab = item.getSlabId();
	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 15.9;
		} else {
			percent = 16.9;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 2) {
			percent = 18.5;
		} else {
			percent = 19.5;
		}
	} else {
		if (slab == 3) {
			percent = 20.0;
		} else {
			percent = 22;
		}
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Large scale Profit Private Class A organization)", percent,
			fraction));
end      
 
rule "Small Scale Profit Private Class B Federal base rule" #Base Tax
salience 49
when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.SMALL) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 && ((categoryId == Organization.Category.getId(Organization.Category.INSURANCE) ) || (categoryId==Organization.Category.getId(Organization.Category.FINANCE)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ENTERTAINMENT) ) || (categoryId == Organization.Category.getId(Organization.Category.AUTOMOBILE) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 14;

	int slabId = item.getSlabId();
	if (slabId == 2) {
		percent = percent * 0.9;
	} else if (slabId == 3) {
		percent = percent * 1.2;
	} else {
		percent = percent * 1.4;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Small scale Profit Private Class B organization)", percent,
			fraction));
end
 
 rule "Small Scale Profit Private Class B State tax rule" #Base Tax
 salience 49
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.SMALL) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 && ((categoryId == Organization.Category.getId(Organization.Category.INSURANCE) ) || (categoryId==Organization.Category.getId(Organization.Category.FINANCE)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ENTERTAINMENT) ) || (categoryId == Organization.Category.getId(Organization.Category.AUTOMOBILE) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 0;

	int slabId = item.getSlabId();
	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slabId == 1) {
			percent = 13.2;
		} else {
			percent = 14.9;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slabId == 1) {
			percent = 15.5;
		} else {
			percent = 16.5;
		}
	} else {
		if (slabId == 1) {
			percent = 17.0;
		} else {
			percent = 18;
		}
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Small scale Profit Private Class B organization)", percent,
			fraction));
end   
 
 
rule "Medium Scale Profit Private Class B Federal base rule" #Base Tax
salience 49
 when
	item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.MEDIUM) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.INSURANCE) ) || (categoryId==Organization.Category.getId(Organization.Category.FINANCE)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ENTERTAINMENT) ) || (categoryId == Organization.Category.getId(Organization.Category.AUTOMOBILE) )
	 ))
	taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 19;

	int slabId = item.getSlabId();
	if (slabId == 2) {
		percent = percent * 1.1;
	} else if (slabId == 3) {
		percent = percent * 1.25;
	} else {
		percent = percent * 1.6;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Medium scale Profit Private Class B organization)", percent,
			fraction));
end
 
 rule "Medium Scale Profit Private Class B State tax rule" #Base Tax
 salience 47
when
	item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.MEDIUM) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.INSURANCE) ) || (categoryId==Organization.Category.getId(Organization.Category.FINANCE)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ENTERTAINMENT) ) || (categoryId == Organization.Category.getId(Organization.Category.AUTOMOBILE) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 0;

	int slab = item.getSlabId();
	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 14.2;
		} else {
			percent = 15.9;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 1) {
			percent = 15.9;
		} else {
			percent = 17;
		}
	} else {
		if (slab == 1) {
			percent = 17.5;
		} else {
			percent = 18.5;
		}
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Medium scale Profit Private Class B organization)", percent,
			fraction));
end  
 
 
 
rule "Large Scale Profit Private Class B Federal base rule" #Base Tax
salience 49
when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.LARGE) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.INSURANCE) ) || (categoryId==Organization.Category.getId(Organization.Category.FINANCE)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ENTERTAINMENT) ) || (categoryId == Organization.Category.getId(Organization.Category.AUTOMOBILE) )
	 ))
	 taxRecord:TaxRecord()
then
	double amount = item.getTaxableIncome();
	double percent = 28;

	int slabId = item.getSlabId();
	if (slabId == 2) {
		percent = percent * 1.1;
	} else if (slabId == 3) {
		percent = percent * 1.2;
	} else {
		percent = percent * 1.35;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Large scale Profit Private Class B organization)", percent,
			fraction));
end
 
 rule "Large Scale Profit Private Class B State tax rule" #Base Tax
 salience 47
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.LARGE) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.INSURANCE) ) || (categoryId==Organization.Category.getId(Organization.Category.FINANCE)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ENTERTAINMENT) ) || (categoryId == Organization.Category.getId(Organization.Category.AUTOMOBILE) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 0;

	int slab = item.getSlabId();
	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 14.9;
		} else {
			percent = 13.9;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 2) {
			percent = 12.5;
		} else {
			percent = 16.5;
		}
	} else {
		if (slab == 3) {
			percent = 21.0;
		} else {
			percent = 22.8;
		}
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Large scale Profit Private Class B organization)", percent,
			fraction));
 end      
 
 
 
 rule "Small Scale Profit Private Class C Federal base rule" #Base Tax
salience 45
when
	 item:Organization(scaleId == Organization.Scale.getId(Organization.Scale.SMALL) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.INFORMATION_TECHNOLOGY)) || (categoryId==Organization.Category.getId(Organization.Category.CHEMICALS)) ||
	 (categoryId == Organization.Category.getId(Organization.Category.PETROLEUM) ) || (categoryId == Organization.Category.getId(Organization.Category.REAL_ESTATE))
	 ))
	 taxRecord:TaxRecord()
then
	double amount = item.getTaxableIncome();
	double percent = 15;

	int slabId = item.getSlabId();

	if (slabId == 2) {
		percent = percent * 0.5;
	} else if (slabId == 3) {
		percent = percent * 0.7;
	} else {
		percent = percent * 1.1;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Small scale Profit Private Class C organization)", percent, fraction));
 end
 
 rule "Small Scale Profit Private Class C State tax rule" #Base Tax
 salience 43
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.SMALL) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.INFORMATION_TECHNOLOGY) ) || (categoryId==Organization.Category.getId(Organization.Category.CHEMICALS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.PETROLEUM) ) || (categoryId == Organization.Category.getId(Organization.Category.REAL_ESTATE) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 13;

	int slab = item.getSlabId();

	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 11.9;
		} else {
			percent = 21.9;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 1) {
			percent = 11.5;
		} else {
			percent = 18.5;
		}
	}else {
		if (slab == 1) {
			percent = 19.0;
		} else {
			percent = 12;
		}
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Small scale Profit Private Class C organization)", percent,
			fraction));
end   
 
 
 rule "Medium Scale Profit Private Class C Federal base rule" #Base Tax
 salience 45
 when
	item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.MEDIUM) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.INFORMATION_TECHNOLOGY) ) || (categoryId==Organization.Category.getId(Organization.Category.CHEMICALS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.PETROLEUM) ) || (categoryId == Organization.Category.getId(Organization.Category.REAL_ESTATE) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 15;

	int slabId = item.getSlabId();

	if (slabId == 2) {
		percent = percent * 0.6;
	} else if (slabId == 3) {
		percent = percent * 1.3;
	} else {
		percent = percent * 1.4;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Medium scale Profit Private Class C organization)", percent,
				fraction));   
end
 
 rule "Medium Scale Profit Private Class C State tax rule" #Base Tax
 salience 43
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.MEDIUM) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.INFORMATION_TECHNOLOGY) ) || (categoryId==Organization.Category.getId(Organization.Category.CHEMICALS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.PETROLEUM) ) || (categoryId == Organization.Category.getId(Organization.Category.REAL_ESTATE) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 0;

	int slab = item.getSlabId();
	
	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 14.5;
		} else {
			percent = 15.5;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 2) {
			percent = 14.5;
		} else {
			percent = 16.5;
		}
	}
	else {
		if (slab == 3) {
			percent = 15.3;
		} else {
			percent = 18;
		}
	}
	
	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Medium scale Profit Private Class C organization)", percent,
			fraction)); 
end  
 
 
 
rule "Large Scale Profit Private Class C Federal base rule" #Base Tax
salience 45
 when
	item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.LARGE) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.INFORMATION_TECHNOLOGY) ) || (categoryId==Organization.Category.getId(Organization.Category.CHEMICALS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.PETROLEUM) ) || (categoryId == Organization.Category.getId(Organization.Category.REAL_ESTATE) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 25;

	int slabId = item.getSlabId();
	if (slabId == 2) {
		percent = percent * 1.2;
	} else if (slabId == 3) {
		percent = percent * 1.4;
	} else {
		percent = percent * 1.6;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Large scale Profit Private Class C organization)", percent,
			fraction));
end
 
 rule "Large Scale Profit Private Class C State tax rule" #Base Tax
 salience 43
  when
	  item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.LARGE) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.INFORMATION_TECHNOLOGY) ) || (categoryId==Organization.Category.getId(Organization.Category.CHEMICALS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.PETROLEUM) ) || (categoryId == Organization.Category.getId(Organization.Category.REAL_ESTATE) )
	 ))
	 taxRecord:TaxRecord()
then
	double amount = item.getTaxableIncome();
	double percent = 0;

	int slab = item.getSlabId();
	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 21.9;
		} else {
			percent = 25.9;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 2) {
			percent = 23.5;
		} else {
			percent = 27.5;
		}
	} else {
		if (slab == 3) {
			percent = 21.0;
		} else {
			percent = 22.8;
		}
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Large scale Profit Private Class C organization)", percent,
			fraction));
end      
 
  
 rule "Small Scale Profit Private Class D Federal base rule" #Base Tax
salience 44
when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.SMALL) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.TRANSPORT) ) || (categoryId==Organization.Category.getId(Organization.Category.LOGISTICS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.TELECOMMUNICATION) ) || (categoryId == Organization.Category.getId(Organization.Category.MANUFACTURING) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 24;

	int slabId = item.getSlabId();

	if (slabId == 2) {
		percent = percent * 1.5;
	} else if (slabId == 3) {
		percent = percent * 1.3;
	} else {
		percent = percent * 1.18;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Small scale Profit Private Class D organization)", percent, fraction));
end
 
 rule "Small Scale Profit Private Class D State tax rule"
 salience 42
when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.SMALL) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.TRANSPORT) ) || (categoryId==Organization.Category.getId(Organization.Category.LOGISTICS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.TELECOMMUNICATION) ) || (categoryId == Organization.Category.getId(Organization.Category.MANUFACTURING) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 0;

	int slab = item.getSlabId();

	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 13.9;
		} else {
			percent = 15.9;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 1) {
			percent = 14.5;
		} else {
			percent = 16.5;
		}
	}

	else {
		if (slab == 1) {
			percent = 15.0;
		} else {
			percent = 16;
		}
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Small scale Profit Private Class D organization)", percent,
			fraction));
end   
 
 
 rule "Medium Scale Profit Private Class D Federal base rule" #Base Tax
  salience 44
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.MEDIUM) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.TRANSPORT) ) || (categoryId==Organization.Category.getId(Organization.Category.LOGISTICS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.TELECOMMUNICATION) ) || (categoryId == Organization.Category.getId(Organization.Category.MANUFACTURING) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 22;

	int slabId = item.getSlabId();

	if (slabId == 2) {
		percent = percent * 1.5;
	} else if (slabId == 3) {
		percent = percent * 1.3;
	} else {
		percent = percent * 0.8;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Medium scale Profit Private Class D organization)", percent,
				fraction));    
end
 
 rule "Medium Scale Profit Private Class D State tax rule" #Base Tax
 salience 42
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.MEDIUM) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.TRANSPORT) ) || (categoryId==Organization.Category.getId(Organization.Category.LOGISTICS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.TELECOMMUNICATION) ) || (categoryId == Organization.Category.getId(Organization.Category.MANUFACTURING) )
	 ))
	 taxRecord:TaxRecord()
then
	double amount = item.getTaxableIncome();
	double percent = 0;

	int slab = item.getSlabId();
	
	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 8.6;
		} else {
			percent = 5.9;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 2) {
			percent = 4.5;
		} else {
			percent = 6.5;
		}
	}
	else {
		if (slab == 3) {
			percent = 5.0;
		} else {
			percent = 11;
		}
	}
	
	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Medium scale Profit Private Class D organization)", percent,
			fraction));  
end  
 
 
 
rule "Large Scale Profit Private Class D Federal base rule"
salience 44
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.LARGE) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 && ((categoryId == Organization.Category.getId(Organization.Category.TRANSPORT) ) || (categoryId==Organization.Category.getId(Organization.Category.LOGISTICS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.TELECOMMUNICATION) ) || (categoryId == Organization.Category.getId(Organization.Category.MANUFACTURING) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 30;

	int slabId = item.getSlabId();
	if (slabId == 2) {
		percent = percent * 1.35;
	} else if (slabId == 3) {
		percent = percent * 1.5;
	} else {
		percent = percent * 1.12;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Large scale Profit Private Class D organization)", percent,
			fraction));
end
 
 rule "Large Scale Profit Private Class D State tax rule"
 salience 42
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.LARGE) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PRIVATE) 
	 && ((categoryId == Organization.Category.getId(Organization.Category.TRANSPORT) ) || (categoryId==Organization.Category.getId(Organization.Category.LOGISTICS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.TELECOMMUNICATION) ) || (categoryId == Organization.Category.getId(Organization.Category.MANUFACTURING) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 0;

	int slab = item.getSlabId();
	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 21.2;
		} else {
			percent = 16.2;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 2) {
			percent = 12.3;
		} else {
			percent = 17.3;
		}
	} else {
		if (slab == 3) {
			percent = 21.3;
		} else {
			percent = 25.7;
		}
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Large scale Profit Private Class D organization)", percent,
			fraction));
end                 
  
rule "Small Scale Profit Public Class A Federal base rule" #Base Tax
salience 40
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.SMALL) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 && ((categoryId == Organization.Category.getId(Organization.Category.AGRICULTURE) ) || (categoryId==Organization.Category.getId(Organization.Category.EDUCATIONAL)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ARMY) ) || (categoryId == Organization.Category.getId(Organization.Category.HEALTH) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 20;

	int slabId = item.getSlabId();

	if (slabId == 2) {
		percent = percent * 0.5;
	} else if (slabId == 3) {
		percent = percent * 0.7;
	} else {
		percent = percent * 1.1;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Small scale Profit Public Class A organization)", percent, fraction));
 end
 
 rule "Small Scale Profit Public Class A State tax rule" #Base Tax
 salience 38
 when
	  item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.SMALL) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 && ((categoryId == Organization.Category.getId(Organization.Category.AGRICULTURE) ) || (categoryId==Organization.Category.getId(Organization.Category.EDUCATIONAL)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ARMY) ) || (categoryId == Organization.Category.getId(Organization.Category.HEALTH) )
	 ))
	 taxRecord:TaxRecord()
then 
 	double amount = item.getTaxableIncome();
	double percent = 15;

	int slab = item.getSlabId();

	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 13.9;
		} else {
			percent = 15.9;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 1) {
			percent = 14.5;
		} else {
			percent = 16.5;
		}
	}

	else {
		if (slab == 1) {
			percent = 15.0;
		} else {
			percent = 16;
		}
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Small scale Profit Public Class A organization)", percent,
			fraction));
 end   

 rule "Medium Scale Profit Public Class A Federal base rule"  #Base Tax
salience 40
when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.MEDIUM) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 && ((categoryId == Organization.Category.getId(Organization.Category.AGRICULTURE) ) || (categoryId==Organization.Category.getId(Organization.Category.EDUCATIONAL)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ARMY) ) || (categoryId == Organization.Category.getId(Organization.Category.HEALTH) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 25;

	int slabId = item.getSlabId();

	if (slabId == 2) {
		percent = percent * 0.8;
	} else if (slabId == 3) {
		percent = percent * 0.9;
	} else {
		percent = percent * 1.2;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Medium scale Profit Public Class A organization)", percent,
				fraction));   
end
 
 rule "Medium Scale Profit Public Class A State tax rule" #Base Tax
 salience 38
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.MEDIUM) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 && ((categoryId == Organization.Category.getId(Organization.Category.AGRICULTURE) ) || (categoryId==Organization.Category.getId(Organization.Category.EDUCATIONAL)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ARMY) ) || (categoryId == Organization.Category.getId(Organization.Category.HEALTH) )
	 ))
	 taxRecord:TaxRecord()
then
	double amount = item.getTaxableIncome();
	double percent = 0;

	int slab = item.getSlabId();
	
	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 13.9;
		} else {
			percent = 15.9;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 2) {
			percent = 14.5;
		} else {
			percent = 16.5;
		}
	}
	else {
		if (slab == 3) {
			percent = 15.0;
		} else {
			percent = 16;
		}
	}
	
	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Medium scale Profit Public Class A organization)", percent,
			fraction)); 
end  
 
 
 
 rule "Large Scale Profit Public Class A Federal base rule" #Base Tax
salience 40
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.LARGE) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 && ((categoryId == Organization.Category.getId(Organization.Category.AGRICULTURE) ) || (categoryId==Organization.Category.getId(Organization.Category.EDUCATIONAL)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ARMY) ) || (categoryId == Organization.Category.getId(Organization.Category.HEALTH) )
	 ))
	 taxRecord:TaxRecord()
then
	double amount = item.getTaxableIncome();
	double percent = 25;

	int slabId = item.getSlabId();
	if (slabId == 2) {
		percent = percent * 1.2;
	} else if (slabId == 3) {
		percent = percent * 1.4;
	} else {
		percent = percent * 1.6;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Large scale Profit Public Class A organization)", percent,
			fraction));
end
 
 rule "Large Scale Profit Public Class A State tax rule" #Base Tax
 salience 38
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.LARGE) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 && ((categoryId == Organization.Category.getId(Organization.Category.AGRICULTURE) ) || (categoryId==Organization.Category.getId(Organization.Category.EDUCATIONAL)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ARMY) ) || (categoryId == Organization.Category.getId(Organization.Category.HEALTH) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 0;

	int slab = item.getSlabId();
	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 15.9;
		} else {
			percent = 16.9;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 2) {
			percent = 18.5;
		} else {
			percent = 19.5;
		}
	} else {
		if (slab == 3) {
			percent = 20.0;
		} else {
			percent = 22;
		}
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Large scale Profit Public Class A organization)", percent,
			fraction));
end      
 
rule "Small Scale Profit Public Class B Federal base rule" #Base Tax
salience 39
when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.SMALL) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 && ((categoryId == Organization.Category.getId(Organization.Category.INSURANCE) ) || (categoryId==Organization.Category.getId(Organization.Category.FINANCE)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ENTERTAINMENT) ) || (categoryId == Organization.Category.getId(Organization.Category.AUTOMOBILE) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 14;

	int slabId = item.getSlabId();
	if (slabId == 2) {
		percent = percent * 0.9;
	} else if (slabId == 3) {
		percent = percent * 1.2;
	} else {
		percent = percent * 1.4;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Small scale Profit Public Class B organization)", percent,
			fraction));
end
 
 rule "Small Scale Profit Public Class B State tax rule" #Base Tax
 salience 37
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.SMALL) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 && ((categoryId == Organization.Category.getId(Organization.Category.INSURANCE) ) || (categoryId==Organization.Category.getId(Organization.Category.FINANCE)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ENTERTAINMENT) ) || (categoryId == Organization.Category.getId(Organization.Category.AUTOMOBILE) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 0;

	int slabId = item.getSlabId();
	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slabId == 1) {
			percent = 13.2;
		} else {
			percent = 14.9;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slabId == 1) {
			percent = 15.5;
		} else {
			percent = 16.5;
		}
	} else {
		if (slabId == 1) {
			percent = 17.0;
		} else {
			percent = 18;
		}
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Small scale Profit Public Class B organization)", percent,
			fraction));
end   
 
 
rule "Medium Scale Profit Public Class B Federal base rule" #Base Tax
salience 39
 when
	item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.MEDIUM) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.INSURANCE) ) || (categoryId==Organization.Category.getId(Organization.Category.FINANCE)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ENTERTAINMENT) ) || (categoryId == Organization.Category.getId(Organization.Category.AUTOMOBILE) )
	 ))
	taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 19;

	int slabId = item.getSlabId();
	if (slabId == 2) {
		percent = percent * 1.1;
	} else if (slabId == 3) {
		percent = percent * 1.25;
	} else {
		percent = percent * 1.6;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Medium scale Profit Public Class B organization)", percent,
			fraction));
end
 
 rule "Medium Scale Profit Public Class B State tax rule" #Base Tax
 salience 37
when
	item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.MEDIUM) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.INSURANCE) ) || (categoryId==Organization.Category.getId(Organization.Category.FINANCE)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ENTERTAINMENT) ) || (categoryId == Organization.Category.getId(Organization.Category.AUTOMOBILE) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 0;

	int slab = item.getSlabId();
	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 14.2;
		} else {
			percent = 15.9;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 1) {
			percent = 15.9;
		} else {
			percent = 17;
		}
	} else {
		if (slab == 1) {
			percent = 17.5;
		} else {
			percent = 18.5;
		}
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Medium scale Profit Public Class B organization)", percent,
			fraction));
end  
 
 
 
rule "Large Scale Profit Public Class B Federal base rule" #Base Tax
salience 39
when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.LARGE) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.INSURANCE) ) || (categoryId==Organization.Category.getId(Organization.Category.FINANCE)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ENTERTAINMENT) ) || (categoryId == Organization.Category.getId(Organization.Category.AUTOMOBILE) )
	 ))
	 taxRecord:TaxRecord()
then
	double amount = item.getTaxableIncome();
	double percent = 28;

	int slabId = item.getSlabId();
	if (slabId == 2) {
		percent = percent * 1.1;
	} else if (slabId == 3) {
		percent = percent * 1.2;
	} else {
		percent = percent * 1.35;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Large scale Profit Public Class B organization)", percent,
			fraction));
end
 
 rule "Large Scale Profit Public Class B State tax rule" #Base Tax
 salience 37
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.LARGE) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.INSURANCE) ) || (categoryId==Organization.Category.getId(Organization.Category.FINANCE)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.ENTERTAINMENT) ) || (categoryId == Organization.Category.getId(Organization.Category.AUTOMOBILE) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 0;

	int slab = item.getSlabId();
	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 14.9;
		} else {
			percent = 13.9;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 2) {
			percent = 12.5;
		} else {
			percent = 16.5;
		}
	} else {
		if (slab == 3) {
			percent = 21.0;
		} else {
			percent = 22.8;
		}
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Large scale Profit Public Class B organization)", percent,
			fraction));
 end      
 
 rule "Small Scale Profit Public Class C Federal base rule" #Base Tax
salience 35
when
	 item:Organization(scaleId == Organization.Scale.getId(Organization.Scale.SMALL) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.INFORMATION_TECHNOLOGY)) || (categoryId==Organization.Category.getId(Organization.Category.CHEMICALS)) ||
	 (categoryId == Organization.Category.getId(Organization.Category.PETROLEUM) ) || (categoryId == Organization.Category.getId(Organization.Category.REAL_ESTATE))
	 ))
	 taxRecord:TaxRecord()
then
	double amount = item.getTaxableIncome();
	double percent = 15;

	int slabId = item.getSlabId();

	if (slabId == 2) {
		percent = percent * 0.5;
	} else if (slabId == 3) {
		percent = percent * 0.7;
	} else {
		percent = percent * 1.1;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Small scale Profit Public Class C organization)", percent, fraction));
 end
 
 rule "Small Scale Profit Public Class C State tax rule" #Base Tax
 salience 33
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.SMALL) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.INFORMATION_TECHNOLOGY) ) || (categoryId==Organization.Category.getId(Organization.Category.CHEMICALS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.PETROLEUM) ) || (categoryId == Organization.Category.getId(Organization.Category.REAL_ESTATE) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 13;

	int slab = item.getSlabId();

	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 11.9;
		} else {
			percent = 21.9;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 1) {
			percent = 11.5;
		} else {
			percent = 18.5;
		}
	}else {
		if (slab == 1) {
			percent = 19.0;
		} else {
			percent = 12;
		}
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Small scale Profit Public Class C organization)", percent,
			fraction));
end   
 
 
 rule "Medium Scale Profit Public Class C Federal base rule" #Base Tax
 salience 35
 when
	item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.MEDIUM) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.INFORMATION_TECHNOLOGY) ) || (categoryId==Organization.Category.getId(Organization.Category.CHEMICALS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.PETROLEUM) ) || (categoryId == Organization.Category.getId(Organization.Category.REAL_ESTATE) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 15;

	int slabId = item.getSlabId();

	if (slabId == 2) {
		percent = percent * 0.6;
	} else if (slabId == 3) {
		percent = percent * 1.3;
	} else {
		percent = percent * 1.4;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Medium scale Profit Public Class C organization)", percent,
				fraction));   
end
 
 rule "Medium Scale Profit Public Class C State tax rule" #Base Tax
 salience 33
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.MEDIUM) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.INFORMATION_TECHNOLOGY) ) || (categoryId==Organization.Category.getId(Organization.Category.CHEMICALS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.PETROLEUM) ) || (categoryId == Organization.Category.getId(Organization.Category.REAL_ESTATE) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 0;

	int slab = item.getSlabId();
	
	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 14.5;
		} else {
			percent = 15.5;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 2) {
			percent = 14.5;
		} else {
			percent = 16.5;
		}
	}
	else {
		if (slab == 3) {
			percent = 15.3;
		} else {
			percent = 18;
		}
	}
	
	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Medium scale Profit Public Class C organization)", percent,
			fraction)); 
end  
 
 
 
rule "Large Scale Profit Public Class C Federal base rule" #Base Tax
salience 35
 when
	item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.LARGE) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.INFORMATION_TECHNOLOGY) ) || (categoryId==Organization.Category.getId(Organization.Category.CHEMICALS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.PETROLEUM) ) || (categoryId == Organization.Category.getId(Organization.Category.REAL_ESTATE) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 25;

	int slabId = item.getSlabId();
	if (slabId == 2) {
		percent = percent * 1.2;
	} else if (slabId == 3) {
		percent = percent * 1.4;
	} else {
		percent = percent * 1.6;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Large scale Profit Public Class C organization)", percent,
			fraction));
end
 
 rule "Large Scale Profit Public Class C State tax rule" #Base Tax
 salience 33
  when
	  item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.LARGE) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.INFORMATION_TECHNOLOGY) ) || (categoryId==Organization.Category.getId(Organization.Category.CHEMICALS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.PETROLEUM) ) || (categoryId == Organization.Category.getId(Organization.Category.REAL_ESTATE) )
	 ))
	 taxRecord:TaxRecord()
then
	double amount = item.getTaxableIncome();
	double percent = 0;

	int slab = item.getSlabId();
	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 21.9;
		} else {
			percent = 25.9;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 2) {
			percent = 23.5;
		} else {
			percent = 27.5;
		}
	} else {
		if (slab == 3) {
			percent = 21.0;
		} else {
			percent = 22.8;
		}
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Large scale Profit Public Class C organization)", percent,
			fraction));
end      

 rule "Small Scale Profit Public Class D Federal base rule" #Base Tax
salience 34
when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.SMALL) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.TRANSPORT) ) || (categoryId==Organization.Category.getId(Organization.Category.LOGISTICS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.TELECOMMUNICATION) ) || (categoryId == Organization.Category.getId(Organization.Category.MANUFACTURING) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 24;

	int slabId = item.getSlabId();

	if (slabId == 2) {
		percent = percent * 1.5;
	} else if (slabId == 3) {
		percent = percent * 1.3;
	} else {
		percent = percent * 1.18;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Small scale Profit Public Class D organization)", percent, fraction));
end
 
 rule "Small Scale Profit Public Class D State tax rule"
 salience 32
when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.SMALL) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.TRANSPORT) ) || (categoryId==Organization.Category.getId(Organization.Category.LOGISTICS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.TELECOMMUNICATION) ) || (categoryId == Organization.Category.getId(Organization.Category.MANUFACTURING) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 0;

	int slab = item.getSlabId();

	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 13.9;
		} else {
			percent = 15.9;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 1) {
			percent = 14.5;
		} else {
			percent = 16.5;
		}
	}

	else {
		if (slab == 1) {
			percent = 15.0;
		} else {
			percent = 16;
		}
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Small scale Profit Public Class D organization)", percent,
			fraction));
end   
 
 rule "Medium Scale Profit Public Class D Federal base rule" #Base Tax
  salience 34
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.MEDIUM) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.TRANSPORT) ) || (categoryId==Organization.Category.getId(Organization.Category.LOGISTICS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.TELECOMMUNICATION) ) || (categoryId == Organization.Category.getId(Organization.Category.MANUFACTURING) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 22;

	int slabId = item.getSlabId();

	if (slabId == 2) {
		percent = percent * 1.5;
	} else if (slabId == 3) {
		percent = percent * 1.3;
	} else {
		percent = percent * 0.8;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Medium scale Profit Public Class D organization)", percent,
				fraction));    
end
 
 rule "Medium Scale Profit Public Class D State tax rule" #Base Tax
 salience 32
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.MEDIUM) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 &&( (categoryId == Organization.Category.getId(Organization.Category.TRANSPORT) ) || (categoryId==Organization.Category.getId(Organization.Category.LOGISTICS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.TELECOMMUNICATION) ) || (categoryId == Organization.Category.getId(Organization.Category.MANUFACTURING) )
	 ))
	 taxRecord:TaxRecord()
then
	double amount = item.getTaxableIncome();
	double percent = 0;

	int slab = item.getSlabId();
	
	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 8.6;
		} else {
			percent = 5.9;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 2) {
			percent = 4.5;
		} else {
			percent = 6.5;
		}
	}
	else {
		if (slab == 3) {
			percent = 5.0;
		} else {
			percent = 11;
		}
	}
	
	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Medium scale Profit Public Class D organization)", percent,
			fraction));  
end  
 
rule "Large Scale Profit Public Class D Federal base rule" #Base Tax
salience 34
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.LARGE) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 && ((categoryId == Organization.Category.getId(Organization.Category.TRANSPORT) ) || (categoryId==Organization.Category.getId(Organization.Category.LOGISTICS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.TELECOMMUNICATION) ) || (categoryId == Organization.Category.getId(Organization.Category.MANUFACTURING) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 30;

	int slabId = item.getSlabId();
	if (slabId == 2) {
		percent = percent * 1.35;
	} else if (slabId == 3) {
		percent = percent * 1.5;
	} else {
		percent = percent * 1.12;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Large scale Profit Public Class D organization)", percent,
			fraction));
end
 
 rule "Large Scale Profit Public Class D State tax rule" #Base Tax 
 salience 32
 when
	 item:Organization(scaleId==Organization.Scale.getId(Organization.Scale.LARGE) && typeId==Organization.Type.getId(Organization.Type.PROFIT_PUBLIC) 
	 && ((categoryId == Organization.Category.getId(Organization.Category.TRANSPORT) ) || (categoryId==Organization.Category.getId(Organization.Category.LOGISTICS)  ) ||
	 (categoryId == Organization.Category.getId(Organization.Category.TELECOMMUNICATION) ) || (categoryId == Organization.Category.getId(Organization.Category.MANUFACTURING) )
	 ))
	 taxRecord:TaxRecord()
then 
	double amount = item.getTaxableIncome();
	double percent = 0;

	int slab = item.getSlabId();
	if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
		if (slab == 1) {
			percent = 21.2;
		} else {
			percent = 16.2;
		}
	} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
		if (slab == 2) {
			percent = 12.3;
		} else {
			percent = 17.3;
		}
	} else {
		if (slab == 3) {
			percent = 21.3;
		} else {
			percent = 25.7;
		}
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Base State Tax(Large scale Profit Public Class D organization)", percent,
			fraction));
end      

 rule "Non-Profit-Private Tax Base rule" #Base Tax
 salience 30
 when
	 item:Organization(typeId==Organization.Type.getId(Organization.Type.NON_PROFIT_PRIVATE))
	 taxRecord:TaxRecord()
then
	double amount = item.getTaxableIncome();
	int slabId = item.getSlabId();
	
	double fpercent = item.getTaxPer();
	double spercent = 0;

	if (slabId == 2) {
		fpercent += fpercent * 0.2;
		if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
			spercent = 2;
		} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
			spercent = 2.5;
		} else {
			spercent = 3;
		}
	} else if (slabId == 3) {
		fpercent += fpercent * 0.3;
		if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
			spercent = 3;
		} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
			spercent = 3.5;
		} else {
			spercent = 4;

		}
	} else {
		fpercent += fpercent * 0.4;
		if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
			spercent = 4;
		} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
			spercent = 4.5;
		} else {
			spercent = 5;

		}
	}

	double ftaxcal = Utils.calculatePercentage(amount, fpercent);
	double staxcal = Utils.calculatePercentage(amount, spercent);
	
	taxRecord.addEntry(new Entry("Base Federal Tax(Non-Profit Private organization)", fpercent, ftaxcal));
	taxRecord.addEntry(new Entry("Base State Tax(Non-Profit Private organization)", spercent, staxcal));
end
 
 rule "Non-Profit-Public Tax Base rule" #Base Tax
 salience 30
 when
	 item:Organization(typeId == Organization.Type.getId(Organization.Type.NON_PROFIT_PUBLIC))
	 taxRecord:TaxRecord()
then
	double amount = item.getTaxableIncome();
	double percent = 28;

	int slabId = item.getSlabId();

	double fpercent = item.getTaxPer();
	double spercent = 0;

	if (slabId == 2) {
		fpercent += fpercent * 0.1;
		if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
			spercent = 1;
		} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
			spercent = 1.5;
		} else {
			spercent = 2;
		}
	} else if (slabId == 3) {
		fpercent += fpercent * 0.2;
		if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
			spercent = 2;
		} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
			spercent = 2.5;
		} else {
			spercent = 3;

		}
	}

	else {
		fpercent += fpercent * 0.3;
		if (item.getState().substring(0, 1) == "A" || item.getState().substring(0, 1) == "B") {
			spercent = 3;
		} else if (item.getState().substring(0, 1) == "C" || item.getState().substring(0, 1) == "D") {
			spercent = 3.5;
		} else {
			spercent = 4;
		}
	}

	double ftaxcal = Utils.calculatePercentage(amount, fpercent);
	double staxcal = Utils.calculatePercentage(amount, spercent);
	taxRecord.addEntry(new Entry("Base Federal Tax(Non-Profit Public organization)", fpercent, ftaxcal));
	taxRecord.addEntry(new Entry("Base State Tax(Non-Profit Public organization)", spercent, staxcal));
end
            
 //****** END OF BASE RULES *****/


rule "History 3 years Rule for Organizations" #Tax Rebate
salience 25
when 
	item:Organization( hasLatePayments(3) == true)
	taxRecord:TaxRecord()
then
	double amount = taxRecord.getTotalTax();
	double percent = 18;

	if (item.getTypeId() == Organization.Type.getId(Organization.Type.PROFIT_PRIVATE)) {
		percent = 15;
	} else if (item.getTypeId() == Organization.Type.getId(Organization.Type.PROFIT_PUBLIC)) {
		percent = 7;
	} else if (item.getTypeId() == Organization.Type.getId(Organization.Type.NON_PROFIT_PRIVATE)) {
		percent = 3;
	} else if (item.getTypeId() == Organization.Type.getId(Organization.Type.NON_PROFIT_PUBLIC)) {
		percent = 2;
	}

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Tax Rebate for On-time Payment", percent, -fraction));
end 

rule "Rebate for Organizations invested in Charity" # Tax Rebate
salience 23
when 
	item:Organization()
	investment:Investment(id == 3) from item.getInvestments() 
	taxRecord:TaxRecord()
then
	double amount = investment.getAmount();
	double percent = investment.getApplicablePercent();

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Tax rebate for charity", percent, -fraction));
end

rule "Rebate for Political Investment" # Tax Rebate
salience 21
when 
	item:Organization()
	investment:Investment(id == 4) from item.getInvestments() 
	taxRecord:TaxRecord()
then
	double amount = investment.getAmount();
	double percent = investment.getApplicablePercent();

	double fraction = Utils.calculatePercentage(amount, percent);
	taxRecord.addEntry(new Entry("Tax rebate for political investment", percent, -fraction));
end

rule "Tax Deduction for shares not held" #Tax Deduction
salience 15
when
	item:Organization(SharedExecuted == false)
	taxRecord:TaxRecord()
then
	double amount = taxRecord.getTotalTax();
	double sharePercent = DBHandler.getInstance().getSharePercents(item.getUtin());
	double percent = 100 - sharePercent;
	
	double fraction = Utils.calculatePercentage(amount , percent);
	taxRecord.addEntry(new Entry("Tax Deduction for shares not held", percent, -fraction));
end


rule "Tax for Shares in other organizations"
salience 14
when 
	item:Organization(hasSharesExecuted==false)
	taxRecord:TaxRecord()
then
	Map<Integer, Double> shares = item.getShares();

	int shareUtin = 0;
	double sharePercent = 0;
	double taxForShare = 0;
	
	for (Map.Entry<Integer, Double> entry : shares.entrySet()) {
		shareUtin = entry.getKey();
		sharePercent = entry.getValue();
	
		if (shareUtin != 0) {
			TaxPayer company = DBHandler.getInstance().getTaxPayer(shareUtin);
			((Organization) company).setHasSharesExecuted(true);
			((Organization) company).setSharedExecuted(true);
	
			taxForShare = TaxRulesLogic.triggerRules(company).getTotalTax() * sharePercent;
			taxRecord.addEntry(new Entry("Tax for shares in Organization " + shareUtin, sharePercent, taxForShare));
		}
	}
end
